### ISSUE TITLE
unknown worker class name

### ISSUE THREAD

**Issue by hallefy** [instana/android-agent#1]
im having this error on setup instana on my project...

unknown worker class name: com.instana.android.core.event.worker.EventWorker
        at <PROJECT>.injection.worker.AppWorkFactory.createWorker(AppWorkFactory.kt:22)

**Comment by akaita** [comment]
Hi, 

Could you please share your configuration? 
Even better, a sample project replicating the issue?

**Comment by akaita** [comment]
Closing the issue due to lack of activity. 
Please ping back if necessary.
