### ISSUE TITLE
Error - cannot cast the outer type to a reference type

### ISSUE THREAD

**Issue by mikedtwc** [instana/android-agent#2]
Hi - I'm running into an issue, trying to use Instana for the first time. I change the name, since I'm not sure my employer would be OK with me posting real stuff. 

Whilst processing type 'Lcom/myapp/blah/billing/BlahClass$Companion$getBillingClient$1$bc$1$1;' - cannot cast the outer type to a reference type.  
Signature=Lcom/myapp/blah/blah/BlahClass$Companion$getBillingClient$1$bc$1$1;'; toString()=com.myapp.blah.billing.BlahClass$Companion$getBillingClient$1$bc$1 class=com.myapp.blah.billing.BlahClass$Companion$getBillingClient$1$bc$1
when processing type mungers 
when weaving 
when batch building BuildConfig[null] #Files=0 AopXmls=#0

Is this common? The source file is Kotlin - happens with at least 2 of our files, probably more. I'll try and get it reproduced in a sample project, but so far no luck.

Any help appreciated. Thanks!

**Comment by akaita** [comment]
Hi @mikedtwc , could you share:

- the build log 
- the `myapp/build/ajc-transform.log` file
- the list of plugins applied in `myapp/build.gradle` (in the same order you apply them, please)

note: it is ok if you change all references to `myapp`, that should not matter. If it becomes cumbersome to replace references, you could always use our official support channels where only authorized people would see it.

**Comment by akaita** [comment]
Hi @mikedtwc , 

It's been a while since the last message. We'll be moving support to Zendesk: https://instana.zendesk.com/
Registration is open to everybody, so please feel free to create a ticket there.
